export const HAUTE_HOSPITALITY_TOKENS = {
  name: 'Haute Hospitality',
  colors: {
    surface: '#131313',
    surfaceDim: '#131313',
    surfaceBright: '#393939',
    surfaceContainerLowest: '#0e0e0e',
    surfaceContainerLow: '#1b1c1c',
    surfaceContainer: '#1f2020',
    surfaceContainerHigh: '#2a2a2a',
    surfaceContainerHighest: '#353535',
    onSurface: '#e4e2e1',
    onSurfaceVariant: '#d3c4b7',
    primary: '#c49a6c',
    primaryLight: '#ecbe8e',
    onPrimary: '#2a2a2a',
    surfaceLight: '#f7f7f7',
    onLightText: '#333333',
    pureWhite: '#ffffff',
    error: '#ffb4ab',
    onError: '#690005',
  },
  typography: {
    fontFamilySerif: "'Playfair Display', Georgia, serif",
    fontFamilySans: "'Plus Jakarta Sans', -apple-system, sans-serif",
  },
  geometry: {
    borderRadius: '0px',
  },
  spacing: {
    gutterMobile: '1rem',
    gutterDesktop: '2.5rem',
    marginMobile: '1.25rem',
    marginDesktop: '5rem',
    space2xs: '0.25rem',
    spaceXs: '0.5rem',
    spaceSm: '0.75rem',
    spaceMd: '1.25rem',
    spaceLg: '2rem',
    spaceXl: '3.5rem',
    space2xl: '5.5rem',
    space3xl: '8rem',
  },
} as const;
